export const ADDTOCART = "CART/ADDTOCART";
export const ADDCARTQUANTITY = "CART/ADDCARTQUANTITY";
export const REMOVECARTQUANTITY = "CART/REMOVECARTQUANTITY";
export const DELETEFROMCART = "CART/DELETEFROMCART";
